### ISSUE TITLE
Negative Numbers do not get Type Guessed as NUMERIC

### ISSUE THREAD

**Issue by JVickery-TBS** [ckan/ckanext-xloader#216]
When using type guessing, negative numbers in a column will force any possibilities of NUMERIC and make it TEXT

**Comment by duttonw** [comment]
Hi @JVickery-TBS ,

Just confirm that this is on initial load or on next load with no overrides in the comment field of the table.


I guess more unit tests around this is needed. @ThrawnCA  has been doing good work on ensuring we are not messing up strings by making them a timedelta if too many are how minutes etc.

Could you create a new branch/PR that add's a test by putting in a new column on to https://github.com/ckan/ckanext-xloader/blob/92f7ccaea436a477ac5200ce0bbeb62acd7f29a1/ckanext/xloader/tests/samples/mixed_numeric_string_sample.csv with negative numbers only and update test https://github.com/ckan/ckanext-xloader/blob/92f7ccaea436a477ac5200ce0bbeb62acd7f29a1/ckanext/xloader/tests/test_loader.py#L681 to verify column types (just lower down in the file). Its ok if the test fails if the code is wrong, but does help in fixing in a TDD manner.


---

#### Information on where there may be the fault that causes this issue


https://github.com/ckan/ckanext-xloader/blob/92f7ccaea436a477ac5200ce0bbeb62acd7f29a1/ckanext/xloader/utils.py#L214
```
                for type in list(guesses[ci].keys()):
                    if not isinstance(cell, type):
                        guesses[ci].pop(type)
```

it seems it might use TYPES just above it, but that is the default listing. ```TYPES = [int, bool, str, datetime.datetime, float, Decimal]```  but its not, since its got a list being passed in and only TYPE_MAPPING can be overriden which is used later on (not in guessing :/ ) the types list in both places have the same ordering of args.

Overall, I get the feeling that this was not given as much rigours uplift like the import system since there was always a default item of just go with string with override on next import. Per the readme (which may need to change since it does do some type guessing where possible)

> XLoader - loads all the cells as text, before allowing the admin to convert columns to the types they want (using the Data Dictionary feature). In future it could do automatic detection and conversion.

https://github.com/ckan/ckanext-xloader/blob/92f7ccaea436a477ac5200ce0bbeb62acd7f29a1/ckanext/xloader/loader.py#L478
```
_TYPE_MAPPING = {    "<type 'unicode'>": 'text',    "<type 'bool'>": 'text',    "<type 'int'>": 'numeric',    "<type 'float'>": 'numeric',    "<class 'decimal.Decimal'>": 'numeric',    "<class 'str'>": 'text',    "<class 'bool'>": 'text',    "<class 'int'>": 'numeric',    "<class 'float'>": 'numeric', "<class 'datetime.datetime'>": 'timestamp',}

def get_types():
    _TYPES = [int, bool, str, datetime.datetime, float, Decimal]
    TYPE_MAPPING = config.get('TYPE_MAPPING', _TYPE_MAPPING)
    return _TYPES, TYPE_MAPPING

```

**Comment by JVickery-TBS** [comment]
@duttonw I think this could have just been my fork being outdated with master (or something wrong with my local setup).

https://github.com/ckan/ckanext-xloader/pull/217

I have expanded the mixed numbers tests a bit and seems to be fine and does type guess to NUMERIC
